# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-06 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='merchantaccount',
            name='refresh_token',
        ),
    ]
