# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20170611_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantaccount',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
