"""
Django settings for mycakebox project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import urlparse
import dj_database_url
import boto
from boto.s3.key import Key
import boto.s3.connection

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'merchant',
    'rider',
    'booking',
    'frontend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mycakebox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mycakebox.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

urlparse.uses_netloc.append('mysql')
try:

    # Check to make sure DATABASES is set in settings.py file.
    # If not default to {}

    if 'DATABASES' not in locals():
        DATABASES = {}

    if 'mysql://bad2d2932f9a7e:9c047330@us-cdbr-iron-east-03.cleardb.net/heroku_7499fc2e8e12652' in os.environ:
        url = urlparse.urlparse(os.environ['mysql://bad2d2932f9a7e:9c047330@us-cdbr-iron-east-03.cleardb.net/heroku_7499fc2e8e12652'])

        # Ensure default database exists.
        DATABASES['default'] = DATABASES.get('default', {})

        # Update with environment configuration.
        DATABASES['default'].update({
            'NAME': 'heroku_7499fc2e8e12652',
            'USER': 'bad2d2932f9a7e',
            'PASSWORD': '9c047330',
            'HOST': 'us-cdbr-iron-east-03.cleardb.net',
            'PORT': '3306',
        })
        if self.connection.open:
            self.connection.stat()

        try:
            self.connection = MySQLdb.connect(host='us-cdbr-iron-east-03.cleardb.net',port='3306',db='heroku_7499fc2e8e12652',user='bad2d2932f9a7e',passwd='9c047330')
        except MySQLdb.OperationalError, e:
            self.connection = None


        if url.scheme == 'mysql':
            DATABASES['default']['ENGINE'] = 'django.db.backends.mysql'
except Exception:
    print 'Unexpected error:', sys.exc_info()

DATABASES['default'] = dj_database_url.config(default='mysql://mycakebox_admin:cecore@127.0.0.1:3306/mycakebox')
DATABASES['default']['OPTIONS'] = {
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATETIME_INPUT_FORMATS = (
    '%d/%m/%Y',
    '%d/%m/%y',
    '%y/%m/%d'
    )
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, "static_src", "static_root")

# MEDIA_URL = '/media/'

# MEDIA_ROOT = os.path.join(BASE_DIR, "static_src", "media_root")

DOMAIN_NAME = "http://www.mycakebox.delivery"

TWOFACTOR_API_KEY = "eba5c512-7a7a-11e6-a584-00163ef91450"

TRANSACTIONAL_SMS_URL = "http://2factor.in/API/V1/" + TWOFACTOR_API_KEY + "/ADDON_SERVICES/SEND/TSMS"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static_src", "our_static"),
    )

ANDROID_CLIENT_ID = "efOeHY5Ovf"
ANDROID_CLIENT_SECRET = "r18sAsEsxR"


DEFAULT_TAX_RATE = 0.01 #1%


DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

AWS_S3_HOST = 's3.ap-south-1.amazonaws.com'

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID','')

AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY','')

AWS_STORAGE_BUCKET_NAME = 'mycakebox'

S3_URL = 'http://%s.s3.amazonaws.com' %AWS_STORAGE_BUCKET_NAME

STATIC_DIRECTORY = '/static/'

MEDIA_DIRECTORY = '/media/'

STATIC_URL = S3_URL + STATIC_DIRECTORY

MEDIA_URL = S3_URL + MEDIA_DIRECTORY

ADMIN_MEDIA_PREFIX = S3_URL + STATIC_DIRECTORY + 'admin/'

AWS_QUERYSTRING_AUTH = False