# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notify_rider',
            field=models.BooleanField(default=False),
        ),
    ]
