# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_notify_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_locality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin_locality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='instructions',
            field=models.TextField(default=''),
        ),
    ]
